version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: intl-messageformat
    versions:
    - 9.4.6
    - 9.4.7
    - 9.4.9
    - 9.5.0
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
    - 9.6.10
    - 9.6.3
    - 9.6.4
    - 9.6.6
    - 9.6.7
    - 9.6.8
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
